### PR TITLE
新增4種遊戲模式

### PR DESCRIPTION
**Pull request by YiKaiWu1125**
+ base_processor(不支持改變難度)
+ maze_game_processor
+ maze_video_processor
+ two_player_processor(不支持改變難度)

## Types of changes
**Thanks for sending a pull request! Please fill in the following content to let us know better about this change.**
Please put an `x` in the box that applies

- [ ] **Bugfix**
- [x] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description
改變模式(change_sol) 或改變難度(change_level) 開始 四個方法皆一至
以下範例
```python 
    Camera.processor.change_sol(request.form['game_body'])
```

## More Information
處理問題 #4

### CODE REVIEW

**Review by asas1asas200 — CHANGES_REQUESTED** [review]
Resolve the conflicts before you request a review.

**Comment by asas1asas200** [comment]
This PR is not refactoring, it should be new feature.

**Comment by YiKaiWu1125** [comment]
> Resolve the conflicts before you request a review.

衝突已解決

**Comment by YiKaiWu1125** [comment]
> This PR is not refactoring, it should be new feature.

已修正

**Comment by asas1asas200** [comment]
Don't touch this until I upload a new version.
===

**Comment by YiKaiWu1125** [comment]
> # Don't touch this until I upload a new version.

我很抱歉太晚看到了 好像有改到一大點two_player_processor.py

**Comment by YiKaiWu1125** [comment]
two_player_processor.py `當動作不要太大時`可順利執行

**Comment by YiKaiWu1125** [comment]
待push 重構 maze_video_processor.py

**Comment by asas1asas200** [comment]
Two games implemented.

Check the commits above and force pull into your local repo:
```bash
git fetch --all
git reset --hard origin/maze_video_twoplayer_model
git pull origin maze_video_twoplayer_model
```

According the game class, implement other games.

**Comment by asas1asas200** [comment]
Notice that the `self.sta` was renamed to `self.status`, and the `game_begin_time` and the `game_end time` were renamed to `begin_time` and `end_time`.

**Comment by YiKaiWu1125** [comment]
我修改完成了，這樣前端的頁面要多加兩個選項嗎

**Comment by asas1asas200** [comment]
> 我修改完成了，這樣前端的頁面要多加兩個選項嗎

Yes, and test it if works.

**Comment by asas1asas200** [comment]
I will rewrite the code.

**Comment by YiKaiWu1125** [comment]
ㄚㄚ抱歉太晚看到了， 按鈕剛新增上去了阿

**Comment by asas1asas200** [comment]
@YiKaiWu1125 
Check the last commit and fix the TODOs, then this PR can be merged.

**Comment by asas1asas200** [comment]
No more new features after daabadc.

**Comment by asas1asas200** [comment]
`git pull --rebase` then solve the todo.

No more new features.
===

Don't create the MERGE COMMIT.
===

**Comment by YiKaiWu1125** [comment]
已完成，是這樣嗎

**Pull request merged**
