### PR TITLE
feat(SocketIO): implement websocketio on flask

### PR DESCRIPTION
**Pull request by asas1asas200**
## Types of changes

- [ ] **Bugfix**
- [x] **New feature**
- [x] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [x] **Documentation Update**
- [ ] **Other (please describe)**

## Description

I implemented websocket on this project.
Now it will show a prompt when game over.
Camera will be captured from frontend.

Level selection need to be implemented in the future.

## Steps to Test This Pull Request

Building steps were put in `README.md`.

## Expected behavior

Gaming fps significantly improved.
Display a modal when gameover.

## Related Issue

#9 #21

### CODE REVIEW

**Comment by fcebk17** [comment]
Execution is almost no problem
If re-execute the game mode - warmpup, hands, level1
It can restart the game and camera 
but  the time will continue to count from the first time you enter the game

**Comment by asas1asas200** [comment]
Fixed.

**Comment by YiKaiWu1125** [comment]
會持續發生以下錯誤訊息
  ```shell
post request handler error
Traceback (most recent call last):
  File "C:\Users\kaikai5\Desktop\venv\lib\site-packages\engineio\server.py", line 431, in handle_request
    socket.handle_post_request(environ)
  File "C:\Users\kaikai5\Desktop\venv\lib\site-packages\engineio\socket.py", line 124, in handle_post_request
    p = payload.Payload(encoded_payload=body)
  File "C:\Users\kaikai5\Desktop\venv\lib\site-packages\engineio\payload.py", line 13, in __init__
    self.decode(encoded_payload)
  File "C:\Users\kaikai5\Desktop\venv\lib\site-packages\engineio\payload.py", line 44, in decode
    raise ValueError('Too many packets in payload')
ValueError: Too many packets in payload
```

**Comment by asas1asas200** [comment]
> 會持續發生以下錯誤訊息
> 
> ```shell
> post request handler error
> Traceback (most recent call last):
> File "C:\Users\kaikai5\Desktop\venv\lib\site-packages\engineio\server.py", line 431, in handle_request
>   socket.handle_post_request(environ)
> File "C:\Users\kaikai5\Desktop\venv\lib\site-packages\engineio\socket.py", line 124, in handle_post_request
>   p = payload.Payload(encoded_payload=body)
> File "C:\Users\kaikai5\Desktop\venv\lib\site-packages\engineio\payload.py", line 13, in __init__
>   self.decode(encoded_payload)
> File "C:\Users\kaikai5\Desktop\venv\lib\site-packages\engineio\payload.py", line 44, in decode
>   raise ValueError('Too many packets in payload')
> ValueError: Too many packets in payload
> ```

Hotfix this.
Please check main branch and test it.

**Comment by YiKaiWu1125** [comment]
> > 會持續發生以下錯誤訊息
> > ```shell
> > post request handler error
> > Traceback (most recent call last):
> > File "C:\Users\kaikai5\Desktop\venv\lib\site-packages\engineio\server.py", line 431, in handle_request
> >   socket.handle_post_request(environ)
> > File "C:\Users\kaikai5\Desktop\venv\lib\site-packages\engineio\socket.py", line 124, in handle_post_request
> >   p = payload.Payload(encoded_payload=body)
> > File "C:\Users\kaikai5\Desktop\venv\lib\site-packages\engineio\payload.py", line 13, in __init__
> >   self.decode(encoded_payload)
> > File "C:\Users\kaikai5\Desktop\venv\lib\site-packages\engineio\payload.py", line 44, in decode
> >   raise ValueError('Too many packets in payload')
> > ValueError: Too many packets in payload
> > ```
> 
> Hotfix this. Please check main branch and test it.

可順利執行了

**Pull request merged**
